function makeSea(){
  const sea=new THREE.Mesh(new THREE.CircleGeometry(64,64),new THREE.MeshStandardMaterial({color:0x0b3a52,roughness:.28,metalness:.14,transparent:true,opacity:.96,side:THREE.DoubleSide}));sea.rotation.x=-Math.PI/2;sea.position.y=-2.65;scene.add(sea);sea.userData.sea=true;
  const floor=new THREE.Mesh(new THREE.CircleGeometry(70,48),new THREE.MeshBasicMaterial({color:0x04101b,side:THREE.DoubleSide}));floor.rotation.x=-Math.PI/2;floor.position.y=-4.8;scene.add(floor)
}
function makeStars(){const geo=new THREE.BufferGeometry(),arr=[];for(let i=0;i<800;i++){const r=70+Math.random()*70,a=Math.random()*Math.PI*2,y=12+Math.random()*70;arr.push(Math.cos(a)*r,y,Math.sin(a)*r)}geo.setAttribute('position',new THREE.Float32BufferAttribute(arr,3));const pts=new THREE.Points(geo,new THREE.PointsMaterial({color:0xd9ecff,size:.22,transparent:true,opacity:.75,sizeAttenuation:true}));scene.add(pts)}
function makePaths(){const center=new THREE.Vector3(...POS.meaning);Object.entries(POS).forEach(([id,p])=>{if(id==='meaning')return;const pts=[];for(let i=0;i<=32;i++){const t=i/32;const x=center.x+(p[0]-center.x)*t,z=center.z+(p[2]-center.z)*t,y=-2.25+Math.sin(Math.PI*t)*.3;pts.push(new THREE.Vector3(x,y,z))}const geo=new THREE.BufferGeometry().setFromPoints(pts);const line=new THREE.Line(geo,new THREE.LineBasicMaterial({color:hexNum(COLORS[id]),transparent:true,opacity:.17}));scene.add(line)})}
function makeFireflies(){Object.entries(POS).forEach(([id,p])=>{const geo=new THREE.BufferGeometry(),arr=[];for(let i=0;i<18;i++){const a=Math.random()*Math.PI*2,r=3+Math.random()*4;arr.push(p[0]+Math.cos(a)*r,1.5+Math.random()*5,p[2]+Math.sin(a)*r)}geo.setAttribute('position',new THREE.Float32BufferAttribute(arr,3));const pts=new THREE.Points(geo,new THREE.PointsMaterial({color:hexNum(COLORS[id]),size:.12,transparent:true,opacity:.55}));pts.userData={firefly:true,seed:Math.random()*20};scene.add(pts)})}
function setupScene(){
  scene=new THREE.Scene();scene.background=new THREE.Color(0x07111e);scene.fog=new THREE.FogExp2(0x07111e,.012);
  camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.1,300);cameraTarget=new THREE.Vector3(0,0,0);clock=new THREE.Clock();
  renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.0;$('#stage').appendChild(renderer.domElement);
  const hemi=new THREE.HemisphereLight(0xbfe5ff,0x1b1715,2.15);scene.add(hemi);const moon=new THREE.DirectionalLight(0xffefd3,2.3);moon.position.set(-24,38,-14);moon.castShadow=true;scene.add(moon);const fill=new THREE.DirectionalLight(0x7aa9d8,.8);fill.position.set(30,18,25);scene.add(fill);
  worldGroup=new THREE.Group();scene.add(worldGroup);makeSea();makeStars();makePaths();Object.entries(POS).forEach(([id,pos])=>rockIsland(id,pos));makeFireflies();
  raycaster=new THREE.Raycaster();pointer=new THREE.Vector2();updateCamera();addControls();window.addEventListener('resize',onResize);animate();
}
function updateCamera(){const cp=Math.cos(camPitch);camera.position.set(cameraTarget.x+Math.sin(camYaw)*cp*camDist,cameraTarget.y+Math.sin(camPitch)*camDist,cameraTarget.z+Math.cos(camYaw)*cp*camDist);camera.lookAt(cameraTarget)}
function travelTo(region,dist=15){const p=POS[region];if(!p)return;selectedRegion=region;const start={target:cameraTarget.clone(),dist:camDist,yaw:camYaw,pitch:camPitch};const end={target:new THREE.Vector3(p[0],1.2,p[2]),dist,yaw:camYaw,pitch:.56};travel={start,end,t:0,d:1.35};showRealm(region);setMode(REG[region].name.toUpperCase());qsa('.realm-chip').forEach(b=>b.classList.toggle('active',b.dataset.region===region));}
function worldView(){selectedRegion=null;selectedLandmark=null;closeRealm();const start={target:cameraTarget.clone(),dist:camDist,yaw:camYaw,pitch:camPitch};travel={start,end:{target:new THREE.Vector3(0,0,0),dist:52,yaw:.55,pitch:.72},t:0,d:1.4};setMode('WORLD VIEW');qsa('.realm-chip').forEach(b=>b.classList.remove('active'))}
function flyLandmark(region,name){travelTo(region,13);setTimeout(()=>openLandmark(region,name),520)}
function addControls(){const el=renderer.domElement;
  el.addEventListener('pointerdown',e=>{drag={down:true,x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,moved:0};el.setPointerCapture?.(e.pointerId)});
  el.addEventListener('pointermove',e=>{if(!drag.down)return;const dx=e.clientX-drag.lastX,dy=e.clientY-drag.lastY;drag.lastX=e.clientX;drag.lastY=e.clientY;drag.moved+=Math.abs(dx)+Math.abs(dy);camYaw-=dx*.006;camPitch=Math.max(.18,Math.min(1.25,camPitch+dy*.005));travel=null;updateCamera()});
  el.addEventListener('pointerup',e=>{if(!drag.down)return;drag.down=false;if(drag.moved<12)pick(e.clientX,e.clientY)});
  el.addEventListener('wheel',e=>{e.preventDefault();camDist=Math.max(9,Math.min(64,camDist+Math.sign(e.deltaY)*2.2));travel=null;updateCamera()},{passive:false});
  el.addEventListener('touchstart',e=>{if(e.touches.length===2)pinchDist=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY)},{passive:true});
  el.addEventListener('touchmove',e=>{if(e.touches.length===2&&pinchDist){const d=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);camDist=Math.max(9,Math.min(64,camDist-(d-pinchDist)*.035));pinchDist=d;travel=null;updateCamera()}},{passive:true});
  el.addEventListener('touchend',()=>pinchDist=0,{passive:true});
}
function pick(x,y){const rect=renderer.domElement.getBoundingClientRect();pointer.x=((x-rect.left)/rect.width)*2-1;pointer.y=-((y-rect.top)/rect.height)*2+1;raycaster.setFromCamera(pointer,camera);const hits=raycaster.intersectObjects(clickable,false);if(!hits.length)return;let u=hits[0].object.userData;if(u.type==='landmark'){travelTo(u.region,13);setTimeout(()=>openLandmark(u.region,u.landmark),600)}else if(u.type==='region')travelTo(u.region)}
function onResize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)}
function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.05),t=clock.elapsedTime;if(travel){travel.t+=dt;const q=Math.min(1,travel.t/travel.d),e=1-Math.pow(1-q,3);cameraTarget.lerpVectors(travel.start.target,travel.end.target,e);camDist=travel.start.dist+(travel.end.dist-travel.start.dist)*e;camYaw=travel.start.yaw+(travel.end.yaw-travel.start.yaw)*e;camPitch=travel.start.pitch+(travel.end.pitch-travel.start.pitch)*e;if(q>=1)travel=null;updateCamera()}
  worldGroup.traverse(o=>{if(o.userData?.flame){o.scale.y=1+Math.sin(t*5)*.08;o.rotation.y+=dt*.7}if(o.userData?.type==='landmark'&&o.userData.floatSeed!=null){o.rotation.y+=dt*.25}});scene.traverse(o=>{if(o.userData?.firefly){o.rotation.y=Math.sin(t*.08+o.userData.seed)*.3}});renderer.render(scene,camera)}
