function setMode(s){$('#modeBadge').textContent=s}
function showRealm(id){const r=REG[id],lms=landmarks(id);const card=$('#realmCard');card.style.setProperty('--c',COLORS[id]);card.innerHTML=`<button class="close-card" id="closeRealmBtn">×</button><div class="eyebrow">${ICON[id]} · REALM</div><h2>${esc(r.name)}</h2><p>${esc(r.tagline)}. This island gathers ${countRegion(id)} sources from your reading archive.</p><div class="meta"><span class="pill">${countRegion(id)} sources</span><span class="pill">${lms.length} landmarks</span></div><div class="landmarks">${lms.map(x=>`<button class="landmark-btn" data-lm="${esc(x)}"><span><b>${esc(x)}</b><small>${BOOKS.filter(b=>b.region===id&&b.landmark===x).length} paths</small></span><span>→</span></button>`).join('')}</div>`;card.classList.add('show');$('#closeRealmBtn').addEventListener('click',closeRealm);card.querySelectorAll('[data-lm]').forEach(b=>b.addEventListener('click',()=>openLandmark(id,b.dataset.lm)))}
function closeRealm(){$('#realmCard').classList.remove('show')}
function openLandmark(region,name){selectedLandmark=name;const books=BOOKS.filter(b=>b.region===region&&b.landmark===name);const c=$('#landmarkContent');c.style.setProperty('--c',COLORS[region]);c.innerHTML=`<div class="sheet-head"><div><div class="sub">${esc(REG[region].name)} · LANDMARK</div><h2>${esc(name)}</h2><div class="sub">${books.length} sources converge here.</div></div><button class="x" data-close="landmarkSheet">×</button></div><div class="book-grid">${books.map(bookCard).join('')}</div>`;$('#landmarkSheet').classList.add('show');wireSheet(c)}
function bookCard(b){return `<button class="book-card" data-book="${b.id}" style="--c:${COLORS[b.region]}"><span class="route">${esc(b.landmark)}</span><b>${esc(b.title)}</b><small>${b.highlight_count?b.highlight_count+' highlights':'Uploaded guide / source text'} · ${b.tags.slice(0,3).join(' · ')}</small></button>`}
function openBook(id){const b=BOOKS.find(x=>x.id===id);if(!b)return;const c=$('#bookContent');c.style.setProperty('--c',COLORS[b.region]);c.innerHTML=`<div class="sheet-head"><div><div class="sub">${esc(REG[b.region].name)} · ${esc(b.landmark)}</div><h2>${esc(b.title)}</h2><div class="sub">${b.highlight_count?b.highlight_count+' highlights detected':'Uploaded guide / source text'} · ${esc(b.tags.join(' · '))}</div></div><button class="x" data-close="bookSheet">×</button></div><div class="quote-list">${b.excerpts.map(q=>`<div class="quote">${esc(q)}</div>`).join('')}</div><button class="primary" id="returnLandmark">Return to ${esc(b.landmark)}</button>`;$('#bookSheet').classList.add('show');wireSheet(c);$('#returnLandmark').addEventListener('click',()=>$('#bookSheet').classList.remove('show'))}
function wireSheet(root){root.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>$('#'+b.dataset.close).classList.remove('show')));root.querySelectorAll('[data-book]').forEach(b=>b.addEventListener('click',()=>openBook(b.dataset.book)))}
function qsa(s){return [...document.querySelectorAll(s)]}
function buildCompass(){const n=$('#compass');n.innerHTML=Object.entries(REG).map(([id,r])=>`<button class="realm-chip" data-region="${id}" style="--c:${COLORS[id]}"><b><span style="color:${COLORS[id]}">${ICON[id]}</span>${esc(r.name)}</b><small>${countRegion(id)} sources</small></button>`).join('');n.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>travelTo(b.dataset.region)))}
function openSearch(){const sh=$('#searchSheet');sh.classList.add('show');const i=$('#searchInput');i.value='';renderSearch('');setTimeout(()=>i.focus(),60)}
function renderSearch(q){q=q.trim().toLowerCase();let list=BOOKS.filter(b=>!q||[b.title,b.landmark,...b.tags,...b.excerpts].join(' ').toLowerCase().includes(q)).slice(0,40);$('#searchResults').innerHTML=list.map(b=>`<button class="result" data-book="${b.id}"><b>${esc(b.title)}</b><small>${esc(REG[b.region].name)} · ${esc(b.landmark)}${b.highlight_count?' · '+b.highlight_count+' highlights':''}</small></button>`).join('')||'<div class="sub">No path found.</div>';$('#searchResults').querySelectorAll('[data-book]').forEach(b=>b.addEventListener('click',()=>openBook(b.dataset.book)))}
function wander(){const b=BOOKS[Math.floor(Math.random()*BOOKS.length)];travelTo(b.region,13);setTimeout(()=>openLandmark(b.region,b.landmark),700)}
function toggleLight(){twilight=!twilight;if(twilight){scene.background.set(0x07111e);scene.fog.color.set(0x07111e);renderer.toneMappingExposure=1;$('#lightBtn').innerHTML='☼ <span class="label">Twilight</span>'}else{scene.background.set(0x6f9db4);scene.fog.color.set(0x7da0ad);renderer.toneMappingExposure=1.35;$('#lightBtn').innerHTML='☾ <span class="label">Night</span>'}}
let enterRequested=false;function hideIntro(){const intro=$('#intro');if(!intro||intro.classList.contains('hide'))return;intro.classList.add('hide');setTimeout(()=>intro.style.display='none',750);setTimeout(()=>$('#guide').classList.add('hide'),5500)}
function bindUI(){buildCompass();$('#homeBtn').addEventListener('click',worldView);$('#wanderBtn').addEventListener('click',wander);$('#lightBtn').addEventListener('click',toggleLight);$('#searchBtn').addEventListener('click',openSearch);$('#searchInput').addEventListener('input',e=>renderSearch(e.target.value));document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>$('#'+b.dataset.close).classList.remove('show')));['searchSheet','landmarkSheet','bookSheet'].forEach(id=>$('#'+id).addEventListener('click',e=>{if(e.target.id===id)e.currentTarget.classList.remove('show')}));$('#enterBtn').addEventListener('click',()=>{enterRequested=true;if(scene){hideIntro()}else{$('#loading').textContent='awakening the world…'}})}
(async()=>{bindUI();try{THREE=await import('https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.module.min.js');setupScene();$('#enterBtn').disabled=false;$('#loading').textContent='the world is awake';if(enterRequested)hideIntro();}catch(err){console.error(err);showFallback('Three.js could not load. This 3D edition needs an internet connection the first time it opens.')}})();
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));}
